"""Cartera de activos de ejemplo (PYME tipo) para probar la aplicación."""

from .engine import Asset

SAMPLE_ASSETS: list[Asset] = [
    Asset("S-01", "Servicio de facturación online", "S", owner="Dir. Financiero",
          description="Aplicación web de facturación a clientes",
          C=4, I=5, D=4, A=4, T=4, safeguard_maturity="L2 - Reproducible pero intuitivo"),
    Asset("D-01", "Base de datos de clientes (datos personales)", "D", owner="DPO",
          description="Datos personales de clientes (RGPD)",
          C=5, I=4, D=4, A=3, T=4, safeguard_maturity="L2 - Reproducible pero intuitivo"),
    Asset("D-02", "Documentación financiera y contable", "D", owner="Dir. Financiero",
          description="Contabilidad, nóminas, impuestos",
          C=4, I=5, D=3, A=3, T=4, safeguard_maturity="L3 - Proceso definido"),
    Asset("SW-01", "ERP corporativo", "SW", owner="IT",
          description="Sistema de gestión empresarial",
          C=4, I=4, D=4, A=3, T=3, safeguard_maturity="L3 - Proceso definido"),
    Asset("SW-02", "Servidor de correo electrónico", "SW", owner="IT",
          description="Correo corporativo",
          C=3, I=3, D=4, A=4, T=2, safeguard_maturity="L2 - Reproducible pero intuitivo"),
    Asset("HW-01", "Servidor principal (on-premise)", "HW", owner="IT",
          description="Servidor físico que aloja ERP y BBDD",
          C=3, I=3, D=5, A=2, T=2, safeguard_maturity="L2 - Reproducible pero intuitivo"),
    Asset("HW-02", "Equipos de usuario (portátiles)", "HW", owner="IT",
          description="Parque de portátiles del personal",
          C=3, I=2, D=3, A=2, T=1, safeguard_maturity="L1 - Inicial / ad hoc"),
    Asset("COM-01", "Red corporativa y conexión a Internet", "COM", owner="IT",
          description="LAN, WiFi y enlace a Internet",
          C=3, I=3, D=4, A=2, T=2, safeguard_maturity="L2 - Reproducible pero intuitivo"),
    Asset("Media-01", "Copias de seguridad", "Media", owner="IT",
          description="Backups en disco y nube",
          C=4, I=4, D=5, A=2, T=2, safeguard_maturity="L3 - Proceso definido"),
    Asset("L-01", "Sala CPD / oficina principal", "L", owner="Servicios Generales",
          description="Centro de proceso de datos y oficinas",
          C=2, I=2, D=4, A=1, T=1, safeguard_maturity="L2 - Reproducible pero intuitivo"),
    Asset("P-01", "Personal IT y administradores", "P", owner="RRHH",
          description="Personal con privilegios sobre los sistemas",
          C=4, I=4, D=4, A=3, T=3, safeguard_maturity="L2 - Reproducible pero intuitivo"),
]
